apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: my-eks-cluster
  region: us-west-2
  version: "1.34"

vpc:
  id: "${vpc-ID}"
  subnets:
    private:
      us-west-2a:
          id: "${subnet-ID}"
      us-west-2b:
          id: "${subnet-ID}"
  # If you want to use privateAccess: true, you should create an EKS VPC endpoint.
  clusterEndpoints:
    publicAccess: true
    privateAccess: false

  nat:
    gateway: Disable

autoModeConfig:
    enabled: true
    nodePools: []